import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import 'normalize.css/normalize.css';

const roboto = Roboto({subsets: ['cyrillic'], weight: ['400']})

export const metadata: Metadata = {
  title: 'Seven winds test',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  )
}
